repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.48.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: check-unused-dependencies
        name: Check for unused dependencies
        entry: npx depcheck
        language: node
        types_or: [javascript, jsx, ts, tsx, json]
        pass_filenames: false
        stages: [pre-commit]

      - id: run-unit-tests
        name: Run unit tests
        entry: npm test
        language: node
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
        stages: [pre-commit]

      - id: build-project
        name: Build project
        entry: npm run build
        language: node
        types_or: [javascript, jsx, ts, tsx, json]
        pass_filenames: false
        stages: [pre-commit]
