FROM amazon/aws-lambda-nodejs:22-x86_64

COPY package*.json tsconfig.json ${LAMBDA_TASK_ROOT}/

RUN npm install

COPY . ${LAMBDA_TASK_ROOT}/

RUN npm run build

CMD [ "./dist/lambda_tracker.pushMsgToDynamo"]