FROM amazon/aws-lambda-nodejs:22-x86_64

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_REGION=$AWS_REGION

COPY package*.json tsconfig.json ${LAMBDA_TASK_ROOT}/

RUN npm ci

COPY . ${LAMBDA_TASK_ROOT}/

RUN npm run build

CMD [ "./dist/lambda_tracker.pushMsgToDynamo"]